---
title: "1.1 — Law and Economics — Class Content"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, February 2, 2021*

# <i class="fas fa-info-circle fa-lg"></i> Overview

Welcome to ECON 315 - Economics of the Law! Today's lesson will be an introduction to the course and the tools — what content we will cover, the assignments, what you will need, and what the field known as ["law and economics"](https://en.wikipedia.org/wiki/Law_and_economics) is about.

If you have not done so, please watch my welcome video, read the announcements in Blackboard, take my survey, and join our class slack channel.

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# <i class="fas fa-book-reader fa-lg"></i> Readings

## Optional/Referenced Readings

- [<i class="fas fa-file-pdf"></i> Ellickson, 1989, "A Hypothesis of Wealth-Maximizing Norms: Evidence from the Whaling Industry"](/readings/Ellickson-1989.pdf)

This week is all introductory, but you may look at Chapter 1 in the textbook if you wish. Otherwise, please heed this message:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">A message to students from the Doggfather himself, <a href="https://twitter.com/SnoopDogg?ref_src=twsrc%5Etfw">@SnoopDogg</a> <a href="https://t.co/wsSANYv8u6">pic.twitter.com/wsSANYv8u6</a></p>&mdash; Ryan Briggs (@ryancbriggs) <a href="https://twitter.com/ryancbriggs/status/1293543531496308736?ref_src=twsrc%5Etfw">August 12, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# <i class="fas fa-chalkboard-teacher"></i> Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.1-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.1-slides.pdf)

# <i class="fas fa-dumbbell"></i> Practice

# <i class="fas fa-laptop-code"></i> Assignments

## Preliminary Survey

Please take the [preliminary survey](/assignment/00-preliminary-survey) on your math background by 11:59 PM Sunday. This will help us all have a productive course together.
