---
title: "2.4 — Relief: Property Rules vs. Liability Rules — Class Content"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, march 2, 2021*

# <i class="fas fa-info-circle fa-lg"></i> Overview

If we follow the Normative Coase & Normative Hobbes “theorems” for achieving an efficient property law system, what would it look like? We begin by answering one of the 4 questions a property system must solve: what remedies are available when property rights are violated? We read another very famous paper by Calabresi and Melamed that outline when it is efficient to use a particular remedy, given the transaction and information costs of the situation (as reflected by the normative Coase & Hobbes approach).

# <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading
- [<i class="fas fa-file-pdf"></i> Calabresi and Melamed, 1972, "Property Rules, Liability Rules, and Inalienability: One View of the Cathedral"](/readings/Calabresi-Melamed-1972.pdf)

## Optional but Useful Reading


## Questions To Help Your Reading

# <i class="fas fa-chalkboard-teacher"></i> Slides

# <i class="fas fa-laptop-code"></i> Assignments

## Discussion Board
