---
title: "Assignments"
slug: assignments
---

## Grade Calculator

- [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/law_grade_calculator/)

Use this tool to calculate your final course grade and predict what grades you would need on remaining assignments to obtain a desired course grade.

### Homeworks

There will be roughly a homework assignment for every lesson. These questions will help check your understanding and mastery of the material, and will be a combination of quantitative, graph, and short answer questions of examples. These will also be good indicators of what to expect on the exams. You may collaborate with other students to work on homeworks, but *each person must turn in an individual assignment*. Homeworks are due *one week* from the class period where we finish a lesson, and must be turned in at the beginning of class. Homeworks will be graded by the T.A. as follows: 70% of the grade for completion, and 30% for one randomly selected question. This is to reward students for putting in a full faith effort to try to reach an answer, even if not every answer ends up being correct. 

### Exams



<span class="newthought">No extra credit is available.</span>
