---
title: "Schedule"
slug: schedule
---

This page contains all of the following resources for each class meeting: 

- <i class="fas fa-info-circle"></i> **Content** materials contains suggested readings, more details about assignments, math appendices, and other helpful resources. I suggest you view these **before** each class.
- <i class="fas fa-chalkboard-teacher"></i> **Slides** are "[Xaringan](https://github.com/yihui/xaringan)" presentations in html that can be opened in any browser^[You can find a downloadable <i class="fas fa-file-pdf"></i> `PDF` in each respective <i class="fas fa-info-circle"></i> **class** page]
- <i class="fas fa-dumbbell"></i> **Practice** problems we work on together in class to prepare for homeworks and exams
- <i class="fas fa-laptop-code"></i> **Assignments** are generally 11:59 PM Sundays on Blackboard

Please note, the lesson numbers and topics (e.g. 1.1) are *my* design, and will not match up with the textbook!

Relevant materials (if applicable, icons will become links) will be posted before class meets.

---

`r blogdown::shortcode("schedule")`
