---
title: "4.3 — Pricing Strategies — Practice Problems"
author: "Ryan Safner"
date: "ECON 306 — Fall 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Promoters of a major college basketball tournament estimate that the demand for tickets for *adults* and by *students* are given by:

$$\begin{aligned}
q_a&=5,000-10p_a\\
q_s&=10,000-100p_s\\
\end{aligned}$$

where $a$ represents adults and $s$ represents students. They estimate that the marginal and average total cost of seating an additional spectator is constant at $10.

## 1. The promoters wish to segment the market and charge adults and students different prices.

### a. For each segment of the market, find the inverse demand function and marginal revenue function.

### b. Find the profit-maximizing quantity and price for each segment. 

### c. How much total profit would the tournament earn if they could price discriminate?

## 2. Now suppose they could not price discriminate, and were forced to charge the same price for all attendees.

### a. Find the total market demand function.

### b. Find the inverse demand function for the total market, and then the marginal revenue function. 

### c. Find the profit-maximizing quantity and price for the whole market. 

### d. How much total profit would the tournament earn if they could not price discriminate?
